
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Feb 03 12:33:35 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 3;
  public static final int CHAR = 25;
  public static final int NAMESPACE = 5;
  public static final int GREATER = 41;
  public static final int LPAREN = 9;
  public static final int SEMI = 16;
  public static final int CONTINUE = 23;
  public static final int LESS = 40;
  public static final int FOR = 21;
  public static final int MINUS = 30;
  public static final int RPAREN = 10;
  public static final int AND = 36;
  public static final int OR = 37;
  public static final int BOOL = 26;
  public static final int COMMA = 17;
  public static final int INC = 31;
  public static final int DIV = 34;
  public static final int PLUS = 29;
  public static final int ASSIGN = 18;
  public static final int IF = 19;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int EQUAL = 38;
  public static final int NEW = 6;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int LCURLY = 13;
  public static final int MOD = 35;
  public static final int NUMBER = 27;
  public static final int BREAK = 22;
  public static final int IDENT = 28;
  public static final int VOID = 4;
  public static final int RCURLY = 14;
  public static final int ELSE = 20;
  public static final int LSQUARE = 11;
  public static final int READ = 8;
  public static final int NOT_EQ = 39;
  public static final int DOUBLEC = 15;
  public static final int RSQUARE = 12;
  public static final int LESS_EQ = 43;
  public static final int PROG = 2;
  public static final int DEC = 32;
  public static final int PRINT = 7;
  public static final int GREATER_EQ = 42;
}

